//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LilSnippers_TEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Suppliers = new HashSet<Supplier>();
        }
    
        public int CountryID { get; set; }
        public string Country1 { get; set; }
    
        public virtual ICollection<Supplier> Suppliers { get; set; }
    }
}
