//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LilSnippers_TEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.StylistTimes = new HashSet<StylistTime>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int EmployeeID { get; set; }
        public string EmpFirstName { get; set; }
        public string EmpLastName { get; set; }
        public string EmpAddress1 { get; set; }
        public string EmpAddress2 { get; set; }
        public string EmpCity { get; set; }
        public Nullable<int> StateID { get; set; }
        public string EmpZIP { get; set; }
        public string EmpPhone { get; set; }
        public string EmpEmail { get; set; }
        public string EmpBirthDate { get; set; }
        public string HireDate { get; set; }
        public Nullable<decimal> HourlyWage { get; set; }
        public string TaxStatus { get; set; }
        public string NumExemptions { get; set; }
        public Nullable<int> EmpPositionID { get; set; }
    
        public virtual EmpPosition EmpPosition { get; set; }
        public virtual State State { get; set; }
        public virtual ICollection<StylistTime> StylistTimes { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
