//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LilSnippers_TEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpPosition
    {
        public EmpPosition()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int EmpPositionID { get; set; }
        public string EmpPosition1 { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
