//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LilSnippers_TEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeAddress
    {
        public HomeAddress()
        {
            this.Clients = new HashSet<Client>();
            this.ParentGuardians = new HashSet<ParentGuardian>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int HomeAddressID { get; set; }
        public string HomeAddress1 { get; set; }
        public string HomeAddress2 { get; set; }
        public string HomeCity { get; set; }
        public Nullable<int> StateID { get; set; }
        public string HomeZIP { get; set; }
        public string HomePhone { get; set; }
        public string HomeEmail { get; set; }
        public Nullable<int> HearAboutID { get; set; }
    
        public virtual ICollection<Client> Clients { get; set; }
        public virtual HearAbout HearAbout { get; set; }
        public virtual State State { get; set; }
        public virtual ICollection<ParentGuardian> ParentGuardians { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
