//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LilSnippers_TEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaType
    {
        public MediaType()
        {
            this.Media = new HashSet<Medium>();
        }
    
        public int MediaTypeID { get; set; }
        public string MediaType1 { get; set; }
    
        public virtual ICollection<Medium> Media { get; set; }
    }
}
