//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LilSnippers_TEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medium
    {
        public int MediaID { get; set; }
        public string MediaTitle { get; set; }
        public int MediaTypeID { get; set; }
    
        public virtual MediaType MediaType { get; set; }
    }
}
