//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LilSnippers_TEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParentGuardian
    {
        public int ParentGuardianID { get; set; }
        public string ParentFirstName { get; set; }
        public string ParentLastName { get; set; }
        public Nullable<int> HomeAddressID { get; set; }
    
        public virtual HomeAddress HomeAddress { get; set; }
    }
}
