//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LilSnippers_TEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Transaction_Details = new HashSet<Transaction_Details>();
        }
    
        public int ProductID { get; set; }
        public string ItemNo { get; set; }
        public string Description { get; set; }
        public string Size { get; set; }
        public Nullable<decimal> CostPerEach { get; set; }
        public Nullable<int> NoPerPack { get; set; }
        public Nullable<decimal> CostPerPack { get; set; }
        public Nullable<decimal> RetailPrice { get; set; }
        public Nullable<short> QtyOnHand { get; set; }
        public Nullable<short> PhysicalCount { get; set; }
        public Nullable<short> QtyOnOrder { get; set; }
        public Nullable<short> ReorderLevel { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> ProductTypeID { get; set; }
        public Nullable<int> SupplierID { get; set; }
    
        public virtual ProductType ProductType { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<Transaction_Details> Transaction_Details { get; set; }
    }
}
