//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LilSnippers_TEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public Transaction()
        {
            this.Transaction_Details = new HashSet<Transaction_Details>();
        }
    
        public int TransactionID { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> HomeAddressID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual HomeAddress HomeAddress { get; set; }
        public virtual ICollection<Transaction_Details> Transaction_Details { get; set; }
    }
}
