//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LilSnippers_TEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_Details
    {
        public int UniqueID { get; set; }
        public int TransactionID { get; set; }
        public string ClientFirstName { get; set; }
        public string ClientLastName { get; set; }
        public int ServiceID { get; set; }
        public Nullable<short> ServiceQuantity { get; set; }
        public int ProductID { get; set; }
        public string ItemNo { get; set; }
        public Nullable<short> ProductQuantity { get; set; }
        public Nullable<decimal> Discount { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Service Service { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
